Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y build-essential git unzip

    git clone https://github.com/wg/wrk.git

    cd wrk
    make

    mv wrk /usr/local/bin

    wrk --version

    
  SHELL
end
